Repository HumanSignal/dm2, pull requests merged in 2022-11, with the labels that each got.

#123 ci: Fix output syntax
  .github/workflows/build.yml
  .github/workflows/git-command.yml
Labels: ci

#122 fix: dev-3673: Navigation using task links is broken
  src/mixins/DataStore/DataStore.js
Labels: fix, Confirmed

#112 fix: DEV-2993: Edit and Delete options are missing for Comments section
  src/sdk/api-config.js
  src/sdk/comments-sdk.js
Labels: fix, Confirmed

#124 fix: DEV-3673: Navigation using task links is broken
  src/stores/AppStore.js
  src/stores/Tabs/store.js
Labels: fix, Confirmed

#125 fix: DEV-3224: Move task to the end on next task
  src/sdk/lsf-sdk.js
Labels: fix

#126 fix: DEV-3736: Keep task if URL is from notification
  src/sdk/lsf-sdk.js
Labels: fix

#128 fix: DEV-3773: Fix Update behavior in Label Stream
  src/sdk/lsf-sdk.js
Labels: fix

#127 feat: DEV-3750: Load task with given comment
  src/sdk/lsf-sdk.js
Labels: feat, Confirmed

#129 fix: DEV-3802: Trigger preload only with `interaction` parameter
  src/sdk/lsf-sdk.js
  src/stores/AppStore.js
Labels: fix

#130 fix: DEV-3754: Memory usage of repeater initialization causing crashes
  src/sdk/lsf-sdk.js
Labels: fix, Confirmed
