Repository HumanSignal/dm2, pull requests merged in 2022-07, with the labels that each got.

#57 fix: DEV-2153: Pagination
  src/mixins/DataStore/DataStore.js
Labels: fix

#75 fix: DEV-2526: Don't crash because of undefined LSF
  src/stores/AppStore.js
Labels: fix

#76 ci: DEV-2803: Integrate LS follow merge
  .github/workflows/sync-pr-ls.yml
  .github/workflows/sync-pr-lse.yml
Labels: ci

#80 ci: Bump Node version
  .github/workflows/build.yml
Labels: ci

#81 fix: DEV-2170: On project open set number of tasks defined by task per page
  src/components/Common/Pagination/Pagination.tsx
  src/components/MainView/DataView/DataView.js
  src/mixins/DataStore/DataStore.js
Labels: fix

#82 fix: DEV-2851: Outliner updated collapse/expand UI
  src/components/Label/Label.js
  src/components/Label/Label.styl
  src/utils/feature-flags.js
Labels: fix

#83 feat: DEV-2885: Add new dm columns
  src/assets/icons/comment_check.svg
  src/assets/icons/comment_red.svg
  src/assets/icons/index.js
  src/components/MainView/DataView/DataView.js
  src/stores/DataStores/tasks.js
  src/stores/Tabs/tab_column.js
  src/utils/feature-flags.js
Labels: feat

#84 fix: Rename Tasks to Actions
  src/components/DataManager/Toolbar/ActionsButton.js
Labels: fix

#87 fix: DEV-2672: Add comment authors as type of cell view
  src/components/CellViews/index.js
Labels: fix

#86 feat: DEV-2887: Comments for annotation editor ui
  src/sdk/api-config.js
  src/sdk/comments-sdk.js
  src/sdk/lsf-sdk.js
  src/stores/AppStore.js
  src/utils/feature-flags.js
Labels: feat

#89 fix: DEV-2672: Comment column icons hot fix
  src/stores/Tabs/tab_column.js
Labels: fix

#90 fix: DEV-2986: reverting confirm for unsaved comments
  src/sdk/lsf-sdk.js
  src/stores/AppStore.js
Labels: fix

#91 fix: DEV-2885: Fix new field with ff off
  src/stores/DataStores/tasks.js
Labels: fix

#92 fix: DEV-2986: Adding guards to task loading to ensure users are warned of unsaved comments
  src/sdk/lsf-sdk.js
  src/stores/AppStore.js
Labels: fix
