Repository HumanSignal/dm2, pull requests merged in 2022-08, with the labels that each got.

#93 feat: DEV-3034: Comments with drafts
  src/sdk/api-config.js
  src/sdk/comments-sdk.js
  src/sdk/lsf-sdk.js
  src/utils/feature-flags.js
Labels: feat

#94 fix: DEV-2672: Add new column decorators to old table
  src/components/MainView/DataViewOld/Table.js
Labels: fix

#95 fix: DEV-3110: Load any missing user data for comments
  src/sdk/api-config.js
  src/sdk/comments-sdk.js
Labels: fix

#73 fix: DEV-2519: Choices selected by default
  src/sdk/lsf-sdk.js
  src/utils/feature-flags.js
Labels: fix

#98 ci: DEV-3253: Add chat ops git command
  .github/workflows/git-command.yml
  .github/workflows/help-command.yml
  .github/workflows/slash-command-dispatch.yml
Labels: ci

#97 fix: DEV-3233: Tasks are not filtered on the filter field change
  src/components/Common/Table/TableHead/TableHead.js
  src/stores/Tabs/store.js
  src/stores/Tabs/tab.js
  src/stores/Tabs/tab_filter.js
Labels: fix
