Repository HumanSignal/dm2, pull requests merged in 2022-09, with the labels that each got.

#100 feat: DEV-2984: Movable columns in DM
  src/components/Common/Resizer/Resizer.js
  src/components/Common/Table/Table.js
  src/components/Common/Table/TableHead/TableHead.js
  src/components/Common/Table/TableHead/TableHead.styl
  src/components/Common/TableOld/Table.js
  src/components/Common/TableOld/TableHead/TableHead.js
  src/components/Common/TableOld/TableHead/TableHead.styl
  src/utils/feature-flags.js
Labels: feat

#101 feat: DEV-1752: Support links to drafts and annotations
  src/sdk/dm-sdk.js
  src/sdk/lsf-sdk.js
  src/utils/feature-flags.js
Labels: feat

#104 feat: DEV-3100: Disable Postpone button from backend
  src/sdk/lsf-sdk.js
  src/stores/DataStores/tasks.js
Labels: feat, Confirmed

#105 fix: DEV-3436: Add comment icons in annotations dropdown
  src/sdk/lsf-sdk.js
Labels: fix, Confirmed

#107 fix: DEV-3494: Filters not working for Annotators in DM
  src/components/Filters/FilterLine/FilterOperation.js
  src/mixins/DataStore/DataStore.js
Labels: fix, Confirmed

#106 feat: DEV-3373: Enable video preview
  src/components/CellViews/AudioCell.js
  src/components/CellViews/VideoCell.js
  src/components/CellViews/index.js
  src/components/Common/MediaPlayer/Duration.js
  src/components/Common/MediaPlayer/MediaPlayer.js
  src/components/Common/MediaPlayer/MediaPlayer.styl
  src/components/Common/MediaPlayer/MediaSeeker.js
  src/components/Common/MediaPlayer/MediaSeeker.styl
  src/components/DataGroups/AudioDataGroup.js
  src/stores/Tabs/tab_column.js
Labels: feat, Confirmed
