Repository HumanSignal/dm2, pull requests merged in 2022-10, with the labels that each got.

#110 fix: DEV-3508: Paging error when refreshing the datamanager
  src/mixins/DataStore/DataStore.js
Labels: fix, Confirmed

#113 fix: DEV-3329: DM tabs disappear after editing taxonomy items
  src/components/CellViews/ImageCell.js
Labels: fix

#115 fix: DEV-3560: Wait for task loading to complete before setting any lsf flags
  src/sdk/lsf-sdk.js
Labels: fix, Confirmed

#119 fix: DEV-3606: Trying to save something that doesn't exist
  src/stores/Tabs/store.js
Labels: fix, Confirmed

#116 feat: DEV-3572: Persist and read virtual annotator filters from local storage as a fallback
  src/stores/AppStore.js
  src/stores/Tabs/store.js
  src/stores/Tabs/tab.js
  src/utils/helpers.ts
Labels: feat, Confirmed
