Repository HumanSignal/dm2, pull requests merged in 2022-12, with the labels that each got.

#131 fix: DEV-3874: Fix polling overflow
  src/stores/AppStore.js
  src/utils/ActivityObserver.ts
Labels: fix, Confirmed

#134 fix: DEV-3958: Remove WASD
  src/sdk/keymap.ts
Labels: fix

#135 fix: DEV-3917: Reinit history after draft applied
  src/sdk/lsf-sdk.js
Labels: fix, Confirmed

#133 feat: DEV-2715: Audio v3 improvements
  src/sdk/lsf-sdk.js
  src/utils/feature-flags.js
Labels: feat

#138 fix: DEV-3734: Hide task counter with ff on
  src/sdk/lsf-sdk.js
  src/utils/feature-flags.js
Labels: fix, Confirmed
