Repository HumanSignal/dm2, pull requests merged in 2023-10, with the labels that each got.

#245 fix: DIA-554: [FE] Sometimes only a subset of Dataset tasks are displ…
  src/components/Common/TableOld/Table.js
  src/components/MainView/DataViewOld/Table.js
  src/components/MainView/GridViewOld/GridView.js
Labels: fix

#233 feat: LEAP-47: Move datamanager into the monorepo
  .babelrc
  .eslintrc.js
  dev-server.js
  get-build.js
  jest.config.ts
  package.json
  project.json
  src/assets/icons/index.js
  src/components/Common/Form/Elements/Select/Select.js
  src/components/Common/TableOld/Table.js
  src/dev.js
  src/index.js
  src/index.ts
  src/sdk/app-create.js
  src/sdk/dm-sdk.js
  src/sdk/lsf-sdk.js
  src/themes/default/variables.styl
  src/utils/helpers.ts
  tsconfig.json
  tsconfig.lib.json
  tsconfig.spec.json
  webpack.config-builder.js
  webpack.config.js
  yarn.lock
Labels: feat

#234 fix: LSDV-5044: Add queTotal to lsfProperties from project
  src/sdk/lsf-sdk.js
  src/stores/AppStore.js
Labels: fix

#247 fix: DIA-548: Grid view in DD does not auto-load next records when user scrolls down
  src/components/MainView/DataViewOld/Table.js
  src/components/MainView/GridViewOld/GridView.js
  src/stores/Tabs/tab.js
Labels: fix

#256 fix: DIA-631: [FE] if associated projects dont get sent back the data-explorer breaks
  src/mixins/DataStore/DataStore.js
Labels: fix

#258 fix: OPTIC-79: Add queueTotal to lsfProperties from project (#234)
  src/sdk/lsf-sdk.js
  src/stores/AppStore.js
Labels: fix

#255 feat: DIA-99: [FE] Create range slider frontend component and add to Semantic Search
  src/stores/Tabs/tab.js
  src/stores/types.js
Labels: feat

#260 fix: LEAP-303: Fix github vulnerabilities
  package.json
  yarn.lock
Labels: fix

#253 fix: OPTIC-113: Draft save on switch history and exit
  src/components/MainView/DataViewOld/Table.js
  src/sdk/lsf-sdk.js
Labels: fix, Confirmed
