Repository HumanSignal/dm2, pull requests merged in 2023-05, with the labels that each got.

#173 chore: LSDV-4894: Update to NodeJS LTS
  .github/workflows/build.yml
  .github/workflows/eslint.yml
  package.json
  webpack.config-builder.js
  yarn.lock
Labels: chore

#180 fix: LSDV-5008: Make DM default width equal to the main menu width in Quick View
  src/stores/Tabs/tab.js
Labels: fix

#176 feat: LOPS-127: Update frontend SemanticSearch component to leverage views and tasks endpoint
  src/components/CandidateTaskView/CandidateTaskView.js
  src/components/Common/SemanticSearch/SemanticSearch.js
  src/components/Common/SemanticSearch/SemanticSearch.styl
  src/components/DataManager/Toolbar/instruments.js
  src/stores/Tabs/tab.js
Labels: feat

#181 feat: LSDV-3104: Task navigation standardization
  __mocks__/svg.js
  jest.config.js
  jest.setup.js
  package-lock.json
  package.json
  src/sdk/__tests__/lsf-sdk.test.tsx
  src/sdk/dm-sdk.js
  src/sdk/lsf-sdk.js
  src/sdk/lsf-utils.ts
  yarn.lock
Labels: feat

#187 fix: LSDV-5115: Fix height of tasks header row on quick view
  src/assets/icons/gear_new_ui.svg
  src/assets/icons/index.js
  src/components/App/App.styl
  src/components/Common/Table/Table.js
  src/components/Common/Table/TableHead/TableHead.js
  src/components/Common/Table/TableHead/TableHead.styl
  src/components/Common/TableOld/Table.js
  src/components/Common/TableOld/TableHead/TableHead.js
  src/components/Common/TableOld/TableHead/TableHead.styl
  src/utils/feature-flags.js
Labels: fix

#185 fix: LSDV-3859: Update outdated thirdparty js dependencies
  get-build.js
  package.json
  yarn.lock
Labels: fix

#190 feat: LSDV-3104: Revert task navigation standardization
  __mocks__/svg.js
  jest.config.js
  jest.setup.js
  package-lock.json
  package.json
  src/sdk/__tests__/lsf-sdk.test.tsx
  src/sdk/dm-sdk.js
  src/sdk/lsf-sdk.js
  src/sdk/lsf-utils.ts
  yarn.lock
Labels: feat

#197 feat: LSDV-5035: Use created_at from draft as the annotation draft_created_at
  src/sdk/lsf-utils.ts
  src/types/Task.ts
  src/utils/feature-flags.js
Labels: feat

#196 fix: LSDV-5192: Change quick view icon and change hover color
  src/assets/icons/gear_new_menu.svg
  src/assets/icons/index.js
  src/components/Common/FieldsButton.js
  src/components/Common/Table/Table.js
  src/components/Common/Table/Table.styl
  src/components/Common/TableOld/Table.js
  src/components/Common/TableOld/Table.styl
Labels: fix
