Repository HumanSignal/dm2, pull requests merged in 2023-11, with the labels that each got.

#262 fix: DIA-643: [FE] max threshold 1 makes it so we cant see results for semantic search
  src/stores/Tabs/tab.js
Labels: fix

#250 fix: OPTIC-124: Save and update have success/fail toast messages
  src/sdk/lsf-sdk.js
Labels: fix, Confirmed

#263 ci: PLATE-723: PLATE-724: Fix Expression injection in Actions
  .github/workflows/sync-pr-ls.yml
  .github/workflows/sync-pr-lse.yml
Labels: ci

#267 fix: DIA-667: [FE] semantic search empty state when no results exist with in selected threshold
  src/components/MainView/DataView/DataView.js
  src/components/MainView/DataViewOld/Table.js
  src/utils/feature-flags.js
Labels: fix

#271 ci: Fix LSO FM Downstream repo
  .github/workflows/sync-pr-ls.yml
Labels: ci

#269 fix: DIA-609: Workspaces
  src/sdk/dm-sdk.js
  src/stores/AppStore.js
Labels: fix

#272 fix: LEAP-409: Update files to match with monorepo
  src/assets/icons/index.js
  src/dev.js
  src/sdk/lsf-sdk.js
  webpack.config-builder.js
Labels: fix, Confirmed

#275 ci: PLATE-675: Add /jira chatops command
  .github/workflows/jira-command.yml
  .github/workflows/slash-command-dispatch.yml
Labels: ci

#276 fix: DIA-736: [FE] disable add to project actions when dataset sync is not complete
  src/components/DataManager/Toolbar/ActionsButton.js
  src/components/DataManager/Toolbar/ActionsButton.styl
  src/stores/Action.js
Labels: fix

#274 fix: DIA-640: [FE] when creating a new dataset and navigating to it tasks request will fire multiple times
  src/stores/Tabs/store.js
Labels: fix
