Repository HumanSignal/dm2, pull requests merged in 2023-09, with the labels that each got.

#223 fix: OPTIC-7: Sum lead time from previous draft on annotation submission
  src/sdk/lsf-sdk.js
Labels: fix

#225 feat: OPTIC-3: Enable users to submit and pause their lead time by returning to the dm list
  src/sdk/lsf-sdk.js
Labels: feat

#231 feat: OPTIC-2: Save draft on leave
  src/components/MainView/DataView/DataView.js
  src/components/MainView/DataViewOld/Table.js
  src/sdk/lsf-sdk.js
  src/utils/feature-flags.js
Labels: feat

#232 fix: LOPS-370: We could improve grid view for textual dataset
  src/components/CandidateTaskView/CandidateTaskView.js
  src/components/CandidateTaskView/CandidateTaskView.styl
  src/components/CandidateTaskView/index.js
  src/components/Common/SkeletonLoader/SkeletonGap.tsx
  src/components/Common/SkeletonLoader/SkeletonLine.tsx
  src/components/Common/SkeletonLoader/SkeletonLoader.styl
  src/components/Common/SkeletonLoader/SkeletonLoader.tsx
  src/components/Common/SkeletonLoader/index.tsx
  src/components/Common/Table/TableRow/TableRow.js
  src/components/Common/TableOld/TableRow/TableRow.js
  src/components/MainView/DataView/DataView.js
  src/components/MainView/DataViewOld/Table.js
  src/components/MainView/GridView/GridView.js
  src/components/MainView/GridView/GridView.styl
  src/components/MainView/GridViewOld/GridView.js
  src/components/MainView/GridViewOld/GridView.styl
  src/mixins/DataStore/DataStoreItem.js
  src/stores/DataStores/tasks.js
  src/stores/Tabs/tab.js
Labels: fix

#222 feat: LOPS-134: [FE] find similar CandidateTasks
  src/components/Filters/types/String.js
  src/components/Filters/types/Utility.js
  src/stores/Tabs/tab.js
Labels: feat

#237 fix: DIA-431: [FE] We are using 'Tasks' rather than 'Records' on 'Create project with selected tasks' modal
  src/components/DataManager/Toolbar/ActionsButton.js
Labels: fix

#235 fix: DIA-198: [FE] 'txt' option is missing in data_type dropdown
  src/components/CellViews/index.js
Labels: fix

#238 chore: Fix "Conflicting values" during build
  webpack.config-builder.js
Labels: chore

#239 fix: OPTIC-109: Blank draft should not be created when an annotation is submitted
  src/sdk/lsf-sdk.js
  src/stores/AppStore.js
Labels: fix
