Repository HumanSignal/dm2, pull requests merged in 2023-06, with the labels that each got.

#204 fix: LSDV-E-135: Dependabot updates
  yarn.lock
Labels: fix

#198 feat: LOPS-159: [FE] Candidate task front end needs to show associated projects
  src/components/CandidateTaskView/CandidateTaskView.js
  src/components/CandidateTaskView/CandidateTaskView.styl
  src/mixins/DataStore/DataStore.js
  src/stores/DataStores/tasks.js
  src/utils/api-proxy/index.js
Labels: feat

#205 fix: LSDV-5249: Manual security updates
  package.json
  yarn.lock
Labels: fix

#207 fix: LSDV-5249: Manual security updates
  yarn.lock
Labels: fix

#206 feat: LOPS-157: Update Actions dropdown in Data explorer to support multi-level dropdown
  src/components/Common/Dropdown/DropdownComponent.js
  src/components/DataManager/Toolbar/ActionsButton.js
  src/components/DataManager/Toolbar/ActionsButton.styl
  src/stores/Action.js
  src/stores/Assignee.js
  src/stores/DynamicModel.js
  src/stores/Tabs/tab.js
  src/stores/Tabs/tab_column.js
  src/stores/Tabs/tab_filter_type.js
  src/stores/Tabs/tab_selected_items.js
  src/stores/Users.js
  src/stores/types.js
  src/utils/dom.js
Labels: feat

#208 feat: LOPS-45: [FE] Select and export CandidateTasks to an existing Project
  src/components/DataManager/Toolbar/ActionsButton.js
Labels: feat

#209 fix: LOPS-185: [FE] resolve issue affecting semantic search when selecting items then changing text in semantic search
  src/stores/Tabs/tab_selected_items.js
Labels: fix

#211 ci: SRE-541: Dynamic GH org name
  .github/workflows/sync-pr-ls.yml
  .github/workflows/sync-pr-lse.yml
Labels: ci

#213 fix: LSDV-5355: Check before using column id in DM column creation
  src/stores/Tabs/store.js
Labels: fix
