Repository HumanSignal/dm2, pull requests merged in 2023-03, with the labels that each got.

#157 fix: LOPS-25: Update grid images to not be cropped
  src/components/DataGroups/ImageDataGroup.js
  src/components/MainView/GridView/GridView.styl
Labels: breaking, fix

#158 fix: LSDV-4659: Fix hanging tab request
  src/stores/Tabs/store.js
  src/utils/feature-flags.js
Labels: fix

#159 fix: LSDV-4651: Fix column size when data column is not the last column
  src/components/Common/Resizer/Resizer.js
  src/components/Label/Label.js
Labels: breaking, fix

#160 fix: LSDV-4720: Fix datamanager column styles
  src/components/Common/Resizer/Resizer.styl
  src/components/Common/Table/Table.js
  src/components/Common/Table/Table.styl
  src/components/Common/Table/TableHead/TableHead.styl
  src/components/Common/TableOld/Table.js
Labels: breaking, fix

#163 fix: LSDV-4746-1: Only include limited fields for project when polling
  src/stores/AppStore.js
Labels: breaking, fix

#164 feat: LOPS-33: UI page to view listing of CandidateTasks in Dataset
  src/assets/icons/grid.svg
  src/assets/icons/index.js
  src/assets/icons/list.svg
  src/assets/icons/refresh2.svg
  src/components/Common/Button/Button.js
  src/components/Common/Button/Button.styl
  src/components/Common/FiltersPane.js
  src/components/Common/Form/Elements/Input/Input.js
  src/components/Common/Form/Elements/Input/Input.styl
  src/components/Common/RadioGroup/RadioGroup.js
  src/components/Common/RadioGroup/RadioGroup.styl
  src/components/Common/SemanticSearch/SemanticSearch.js
  src/components/Common/SemanticSearch/SemanticSearch.styl
  src/components/DataManager/Toolbar/ActionsButton.js
  src/components/DataManager/Toolbar/RefreshButton.js
  src/components/DataManager/Toolbar/Toolbar.js
  src/components/DataManager/Toolbar/ViewToggle.js
  src/components/DataManager/Toolbar/instruments.js
  src/components/MainView/DataView/DataView.js
  src/components/MainView/DataViewOld/Table.js
  src/sdk/dm-sdk.js
  src/stores/DataStores/tasks.js
  src/utils/feature-flags.js
Labels: breaking, feat
