Repository HumanSignal/dm2, pull requests merged in 2023-02, with the labels that each got.

#146 feat: DEV-3928: Add messages parameter providing into LSF options
  src/sdk/lsf-sdk.js
Labels: breaking, feat, Confirmed

#148 fix: DEV-4033: fix adjustable columns data manager
  src/components/Common/Resizer/Resizer.styl
  src/components/Common/Table/TableHead/TableHead.js
  src/components/Common/TableOld/TableHead/TableHead.js
Labels: breaking, fix

#151 fix: DEV-4033: Hotfix import issue
  src/components/Common/Table/TableHead/TableHead.js
Labels: breaking, fix

#150 feat: LSDV-3936: Task history is stored on the backend
  src/sdk/api-config.js
  src/sdk/lsf-sdk.js
  src/stores/DataStores/tasks.js
Labels: breaking, feat

#137 feat: DEV-4008: Allow quickly select tasks using hotkeys
  src/components/MainView/DataView/DataView.js
  src/components/MainView/DataViewOld/Table.js
  src/mixins/DataStore/DataStore.js
  src/utils/feature-flags.js
Labels: feat

#153 feat: LOPS-12: Frontend spike - adding a new LabelOps page
  src/components/Common/SemanticSearch/SemanticSearch.js
  src/components/Common/SemanticSearch/SemanticSearch.styl
  src/components/DataManager/DataManager.js
  src/components/DataManager/Toolbar/instruments.js
  src/dev.js
  src/sdk/dm-sdk.js
  src/stores/AppStore.js
  src/stores/Tabs/tab.js
  src/utils/feature-flags.js
Labels: breaking, feat
