Repository HumanSignal/dm2, pull requests merged in 2023-01, with the labels that each got.

#132 fix: DEV-3810: Restrict tabs deletion for reviewers
  src/components/Common/Tabs/Tabs.js
  src/components/Common/Tabs/TabsMenu.js
  src/components/DataManager/DataManager.js
  src/components/DataManager/TabTitle.js
  src/sdk/dm-sdk.js
Labels: fix, Confirmed

#143 fix: DEV-4090: Use unique_lock_id in Label Stream
  src/sdk/lsf-sdk.js
  src/stores/AppStore.js
  src/stores/DataStores/tasks.js
Labels: fix, Confirmed

#139 chore: DEV-3994: Add PR checklist template
  .github/pull_request_template.md
Labels: Confirmed, chore

#147 ci: SRE-400: Enable Lint for PR
  .github/workflows/eslint.yml
  package.json
Labels: ci, breaking
