Repository HumanSignal/dm2, pull requests merged in 2024-01, with the labels that each got.

#286 feat: DIA-474: [FE] add new column for DE
  src/components/CellViews/ProjectCell.js
  src/components/CellViews/index.js
Labels: feat

#280 feat: OPTIC-107: Draft saving on view all
  src/components/MainView/DataViewOld/Table.js
  src/sdk/lsf-sdk.js
Labels: feat, Confirmed

#287 feat: DIA-803: [FE] Make associated projects clickable
  src/components/CellViews/ProjectCell.js
Labels: feat

#289 feat: DIA-820: [FE] Make List type columns display as intended type with out the ability for users to change type for Data Discovery
  src/components/Common/Table/TableHead/TableHead.js
  src/components/Common/TableOld/TableHead/TableHead.js
  src/components/MainView/DataView/DataView.js
  src/components/MainView/DataViewOld/Table.js
Labels: feat

#294 fix: OPTIC-152: Uploading a text field but only 'true' is showing up not 'false'
  src/components/CellViews/DateTimeCell.js
  src/components/CellViews/StringCell.js
Labels: fix, Confirmed

#297 ci: PLATE-838: Add actions-hub to git ignore
  .gitignore
Labels: ci

#295 fix: OPTIC-108: Text on grid view should be truncated
  src/components/DataGroups/AudioDataGroup.js
  src/components/DataGroups/TextDataGroup.js
Labels: fix, Confirmed
