Repository HumanSignal/dm2, pull requests merged in 2024-02, with the labels that each got.

#293 fix: OPTIC-218: 'Annotation saved successfully' message is NOT displayed when user exit label stream using 'Submit and exit' option
  src/sdk/lsf-sdk.js
Labels: fix, Confirmed

#299 fix: OPTIC-411: [lsp] Fix Follow Redirects improperly handles URLs in the url.parse() function
  package.json
  yarn.lock
Labels: fix

#305 refactor: OPTIC-429: Remove unused FF ff_front_dev_1470_dm_pagination_010422_short
  src/components/MainView/DataView/DataView.styl
  src/components/MainView/DataView/Table.js
  src/components/MainView/DataView/Table.styl
  src/components/MainView/DataViewOld/Table.js
  src/components/MainView/GridView/GridView.js
  src/components/MainView/GridView/GridView.styl
  src/components/MainView/GridViewOld/GridView.js
  src/components/MainView/GridViewOld/GridView.styl
  src/components/MainView/index.js
  src/mixins/DataStore/DataStore.js
  src/stores/Tabs/tab.js
  src/utils/feature-flags.js
Labels: refactor

#298 fix: LEAP-443: Support small changes in LSF
  src/components/Label/Toolbar/Toolbar.js
  src/sdk/dm-sdk.js
  src/sdk/lsf-sdk.js
Labels: fix, Confirmed

#306 refactor: OPTIC-469: fflag_feat_front_lops_12_label_ops_ui_short removal
  src/components/DataManager/DataManager.js
  src/stores/Tabs/tab.js
  src/utils/feature-flags.js
Labels: feat, Confirmed, refactor
